### ISSUE TITLE
api no longer works?

### ISSUE THREAD

**Issue by yvesx** [yurimalheiros/senticnetapi#2]
I got these in the console: (I pip installed senticnet so I think it's version 0.3.2)

```
>>> sn = Senticnet()
>>> concept_info = sn.concept('love')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/senticnet/senticnet.py", line 22, in concept
    result["polarity"] = self.polarity(concept, parsed_graph)
  File "/Library/Python/2.7/site-packages/senticnet/senticnet.py", line 72, in polarity
    return parsed_graph.objects(predicate=URIRef(predicate_uri)).next().toPython()
StopIteration
>>> polarity = sn.polarity('love')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/senticnet/senticnet.py", line 72, in polarity
    return parsed_graph.objects(predicate=URIRef(predicate_uri)).next().toPython()
StopIteration
>>> semantics = sn.semantics('love')
>>> sentics = sn.sentics('love')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/senticnet/senticnet.py", line 56, in sentics
    sentics[sentic] = parsed_graph.objects(predicate=URIRef(self.senticapi_base_uri+sentic)).next().toPython()
StopIteration
>>> sentics = sn.sentics('love')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/senticnet/senticnet.py", line 56, in sentics
    sentics[sentic] = parsed_graph.objects(predicate=URIRef(self.senticapi_base_uri+sentic)).next().toPython()
StopIteration
>>> 

```

**Comment by esash-28** [comment]
Hi All,

The api for sentic net is not working for me too.. 

from senticnet.senticnet import Senticnet

sn = Senticnet()
concept_info = sn.concept('love')

Traceback (most recent call last):

  File "<ipython-input-1-788e9256bce9>", line 4, in <module>
    concept_info = sn.concept('love')

  File "C:\Users\EmeraldSoul\Anaconda2\lib\site-packages\senticnet\senticnet.py", line 22, in concept
    result["polarity"] = self.polarity(concept, parsed_graph)

  File "C:\Users\EmeraldSoul\Anaconda2\lib\site-packages\senticnet\senticnet.py", line 72, in polarity
    return parsed_graph.objects(predicate=URIRef(predicate_uri)).next().toPython()

StopIteration

This is what I get. Please help.

Thanks a lot, in advance.

Esash

**Comment by yurimalheiros** [comment]
Hi. It seems that you are not using the lastest version of the API.

Try run this:  ```pip install senticnet --upgrade``` to upgrade the package

**Comment by esash-28** [comment]
Hello Yuri,

Thanks a lot. It helped. I'm sorry for such a silly question. Thanks a lot,
again.

With Best Regards,
*Ashraya S Shiva*

**Comment by yurimalheiros** [comment]
Hi! That's fine.

Good luck with your work.
